apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: us.gcr.io/sylvan-plane-349116/nest-gcloud/nest-gcloud:c5fe58d3ce98073390680f9ebc764cdd0848f8ff
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-central1
    commit-sha: c5fe58d3ce98073390680f9ebc764cdd0848f8ff
    gcb-build-id: 00810f64-280e-4b6a-9833-5f2f8d790288
    gcb-trigger-id: be88b6fc-d675-4dd9-b264-9f534bde6c2c
    managed-by: gcp-cloud-build-deploy-cloud-run
  name: nest-gcloud
  namespace: '865460208469'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        client.knative.dev/user-image: us.gcr.io/sylvan-plane-349116/nest-gcloud/nest-gcloud:c5fe58d3ce98073390680f9ebc764cdd0848f8ff
        run.googleapis.com/client-name: cloud-console
      labels:
        commit-sha: c5fe58d3ce98073390680f9ebc764cdd0848f8ff
        gcb-build-id: 00810f64-280e-4b6a-9833-5f2f8d790288
        gcb-trigger-id: be88b6fc-d675-4dd9-b264-9f534bde6c2c
        managed-by: gcp-cloud-build-deploy-cloud-run
      name: nest-gcloud-00015-soj
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: NODE_ENV
          value: production
        image: us.gcr.io/sylvan-plane-349116/nest-gcloud/nest-gcloud:c5fe58d3ce98073390680f9ebc764cdd0848f8ff
        ports:
        - containerPort: 3003
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      serviceAccountName: 865460208469-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
